language: csharp
solution: libsodium-net.sln
git:
  depth: 3

matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      dist: trusty
      os:
      - linux
      env:
      - CFG=CORE
      - TRAVIS_OS_UNAME=$(uname -s)
    - mono: latest
      sudo: required
      os:
      - linux
      env:
      - CFG=MONO
      - TRAVIS_OS_UNAME=$(uname -s)
    - dotnet: 1.0.1
      mono: none
      dist: trusty
      os:
      - osx
      env:
      - CFG=CORE
      - TRAVIS_OS_UNAME=$(uname -s)
    - mono: latest
      sudo: required
      os:
      - osx
      env:
      - CFG=MONO
      - TRAVIS_OS_UNAME=$(uname -s)

install:
 - ./travis/install.sh

before_script:
 - ./travis/build-libsodium.sh

script:
 - ./travis/build.sh
 - ./travis/test.sh
